// Defines
#define XEATD_X 0 //-0.962
#define XEATD_Y 0 //-0.49
#define XEATD_VERDE { 0.22, 0.7, 0.2, 1 }
#define XEATD_VERDE_DARK { 0.157, 0.4, 0.157, 1 }
#define XEATD_ROSSO { 1, 0.22, 0.22, 1 }
#define XEATD_ROSSO_DARK { 0.6, 0.157, 0.157, 1 }
#define XEATD_BLUE { 0.286, 0.561, 1, 1 }
#define XEATD_BLUE_DARK { 0.2, 0.392, 0.698, 1 }

class XEAT_IGUIBack {
	enableSimulation = true;
	moving = 1;
	type = 0;
	idc = 124;
	style = 128;
	text = "";
	colorText[] = { 0, 0, 0, 0 };
	font = "RobotoCondensed";
	sizeEx = 0;
	shadow = 0;
	x = 0.1;
	y = 0.1;
	w = 0.1;
	h = 0.1;
	tooltipColorText[] = { 1, 1, 1, 1 };
	tooltipColorBox[] = { 1, 1, 1, 0 };
	tooltipColorShade[] = { 0, 0, 0, 0.8 };
	colorbackground[] = { "(profilenamespace getvariable ['IGUI_BCG_RGB_R',0])", "(profilenamespace getvariable ['IGUI_BCG_RGB_G',1])", "(profilenamespace getvariable ['IGUI_BCG_RGB_B',1])", "(profilenamespace getvariable ['IGUI_BCG_RGB_A',0.8])" };
};
class XEAT_RscText {
	enableSimulation = true;
	moving = 1;
	deletable = 0;
	fade = 0;
	access = 0;
	type = 0;
	idc = -1;
	colorBackground[] = { 0, 0, 0, 0 };
	colorText[] = { 1, 1, 1, 1 };
	text = "";
	fixedWidth = 0;
	x = 0;
	y = 0;
	h = 0.037;
	w = 0.3;
	style = 0;
	shadow = 1;
	colorShadow[] = { 0, 0, 0, 0.5 };
	font = "RobotoCondensed";
	SizeEx = "(((((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 1)";
	linespacing = 1;
	tooltipColorText[] = { 1, 1, 1, 1 };
	tooltipColorBox[] = { 1, 1, 1, 0 };
	tooltipColorShade[] = { 0, 0, 0, 0.8 };
};
class XEAT_RscButton {
	enableSimulation = true;
	moving = 1;
	deletable = 0;
	fade = 0;
	access = 0;
	type = 1;
	text = "";
	colorText[] = { 1, 1, 1, 1 };
	colorDisabled[] = { 1, 1, 1, 0.25 };
	colorBackground[] = { 0, 0, 0, 0.5 };
	colorBackgroundDisabled[] = { 0, 0, 0, 0.5 };
	colorBackgroundActive[] = { 0, 0, 0, 1 };
	colorFocused[] = { 0, 0, 0, 1 };
	colorShadow[] = { 0, 0, 0, 0 };
	colorBorder[] = { 0, 0, 0, 1 };
	soundEnter[] = { "\A3\ui_f\data\sound\RscButton\soundEnter", 0.09, 1 };
	soundPush[] = { "\A3\ui_f\data\sound\RscButton\soundPush", 0.09, 1 };
	soundClick[] = { "\A3\ui_f\data\sound\RscButton\soundClick", 0.09, 1 };
	soundEscape[] = { "\A3\ui_f\data\sound\RscButton\soundEscape", 0.09, 1 };
	idc = -1;
	style = 2;
	x = 0;
	y = 0;
	w = 0.095589;
	h = 0.039216;
	shadow = 2;
	font = "RobotoCondensed";
	sizeEx = "(((((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 1)";
	url = "";
	offsetX = 0;
	offsetY = 0;
	offsetPressedX = 0;
	offsetPressedY = 0;
	borderSize = 0;
	tooltipColorText[] = { 1, 1, 1, 1 };
	tooltipColorBox[] = { 1, 1, 1, 0 };
	tooltipColorShade[] = { 0, 0, 0, 0.8 };
};
class XEAT_RscEdit {
	enableSimulation = true;
	moving = 1;
	deletable = 0;
	fade = 0;
	access = 0;
	type = 2;
	x = 0;
	y = 0;
	h = 0.04;
	w = 0.2;
	colorBackground[] = { 0, 0, 0, 0.5 };
	colorText[] = { 1, 1, 1, 1 };
	colorDisabled[] = { 1, 1, 1, 1 };
	colorSelection[] = { 0.2, 0.392, 0.698, 1 };
	autocomplete = "";
	text = "";
	size = 0.2;
	style = "0x00 + 0x40";
	font = "RobotoCondensed";
	shadow = 2;
	sizeEx = "(((((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 1)";
	canModify = 1;
	tooltipColorText[] = { 1, 1, 1, 1 };
	tooltipColorBox[] = { 1, 1, 1, 0 };
	tooltipColorShade[] = { 0, 0, 0, 0.8 };
};
class XEAT_RscCombo {
	enableSimulation = true;
	moving = 1;
	deletable = 0;
	fade = 0;
	access = 0;
	type = 4;
	colorSelect[] = { 1, 1, 1, 1 };
	colorText[] = { 1, 1, 1, 1 };
	colorBackground[] = { 0, 0, 0, 0.5 };
	colorScrollbar[] = { 1, 0, 0, 1 };
	colorDisabled[] = { 1, 1, 1, 0.25 };
	colorPicture[] = { 1, 1, 1, 1 };
	colorPictureSelected[] = { 1, 1, 1, 1 };
	colorPictureDisabled[] = { 1, 1, 1, 0.25 };
	colorPictureRight[] = { 1, 1, 1, 1 };
	colorPictureRightSelected[] = { 1, 1, 1, 1 };
	colorPictureRightDisabled[] = { 1, 1, 1, 0.25 };
	colorTextRight[] = { 1, 1, 1, 1 };
	colorSelectRight[] = { 0, 0, 0, 1 };
	colorSelect2Right[] = { 0, 0, 0, 1 };
	tooltipColorText[] = { 1, 1, 1, 1 };
	tooltipColorBox[] = { 1, 1, 1, 0 };
	tooltipColorShade[] = { 0, 0, 0, 0.8 };
	soundSelect[] = { "\A3\ui_f\data\sound\RscCombo\soundSelect", 0.1, 1 };
	soundExpand[] = { "\A3\ui_f\data\sound\RscCombo\soundExpand", 0.1, 1 };
	soundCollapse[] = { "\A3\ui_f\data\sound\RscCombo\soundCollapse", 0.1, 1 };
	maxHistoryDelay = 1;
	class ComboScrollBar {	
		color[] = {1, 1, 1, 0.6};	
		colorActive[] = {1, 1, 1, 1};	
		colorDisabled[] = {1, 1, 1, 0.3};	
		thumb = "\A3\ui_f\data\gui\cfg\scrollbar\thumb_ca.paa";	
		arrowFull = "\A3\ui_f\data\gui\cfg\scrollbar\arrowFull_ca.paa";	
		arrowEmpty = "\A3\ui_f\data\gui\cfg\scrollbar\arrowEmpty_ca.paa";	
		border = "\A3\ui_f\data\gui\cfg\scrollbar\border_ca.paa";	
	};
	style = "0x10 + 0x200";
	font = "RobotoCondensed";
	sizeEx = "(((((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 1)";
	shadow = 0;
	x = 0;
	y = 0;
	w = 0.12;
	h = 0.035;
	colorSelectBackground[] = { 0.2, 0.392, 0.698, 1 };
	arrowEmpty = "\A3\ui_f\data\GUI\RscCommon\rsccombo\arrow_combo_ca.paa";
	arrowFull = "\A3\ui_f\data\GUI\RscCommon\rsccombo\arrow_combo_active_ca.paa";
	wholeHeight = 0.45;
	colorActive[] = { 1, 0, 0, 1 };
};
class XEAT_RscListBox {
	enableSimulation = true;
	moving = 1;
	deletable = 0;
	fade = 0;
	access = 0;
	type = 5;
	rowHeight = 0;
	colorText[] = { 1, 1, 1, 1 };
	colorDisabled[] = { 1, 1, 1, 0.25 };
	colorScrollbar[] = { 1, 0, 0, 0 };
	colorSelect[] = { 1, 1, 1, 1 };
	colorSelect2[] = { 1, 1, 1, 1 };
	colorSelectBackground[] = { 0.2, 0.392, 0.698, 1 };
	colorSelectBackground2[] = { 0.2, 0.392, 0.698, 1 };
	colorBackground[] = { 0, 0, 0, 0.5 };
	soundSelect[] = { "\A3\ui_f\data\sound\RscListbox\soundSelect", 0.09, 1 };
	autoScrollSpeed = -1;
	autoScrollDelay = 5;
	autoScrollRewind = 0;
	arrowEmpty = "#(argb,8,8,3)color(1,1,1,1)";
	arrowFull = "#(argb,8,8,3)color(1,1,1,1)";
	colorPicture[] = { 1, 1, 1, 1 };
	colorPictureSelected[] = { 1, 1, 1, 1 };
	colorPictureDisabled[] = { 1, 1, 1, 0.25 };
	colorPictureRight[] = { 1, 1, 1, 1 };
	colorPictureRightSelected[] = { 1, 1, 1, 1 };
	colorPictureRightDisabled[] = { 1, 1, 1, 0.25 };
	colorTextRight[] = { 1, 1, 1, 1 };
	colorSelectRight[] = { 0, 0, 0, 1 };
	colorSelect2Right[] = { 0, 0, 0, 1 };
	tooltipColorText[] = { 1, 1, 1, 1 };
	tooltipColorBox[] = { 1, 1, 1, 0 };
	tooltipColorShade[] = { 0, 0, 0, 0.8 };
	class ListScrollBar {	
		color[] = {1, 1, 1, 0.6};	
		colorActive[] = {1, 1, 1, 1};	
		colorDisabled[] = {1, 1, 1, 0.3};	
		thumb = "\A3\ui_f\data\gui\cfg\scrollbar\thumb_ca.paa";	
		arrowFull = "\A3\ui_f\data\gui\cfg\scrollbar\arrowFull_ca.paa";	
		arrowEmpty = "\A3\ui_f\data\gui\cfg\scrollbar\arrowEmpty_ca.paa";	
		border = "\A3\ui_f\data\gui\cfg\scrollbar\border_ca.paa";	
	};
	x = 0;
	y = 0;
	w = 0.3;
	h = 0.3;
	style = 16;
	font = "RobotoCondensed";
	sizeEx = "(((((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 1)";
	shadow = 0;
	colorShadow[] = {0,0,0,0.5};
	period = 1.2;
	maxHistoryDelay = 1;
};
class XEAT_RscCheckBox
{
    idc = -1;
    type = 77;
    style = 0;
    checked = 0;
    x = "0.375 * safezoneW + safezoneX";
    y = "0.36 * safezoneH + safezoneY";
    w = "0.025 * safezoneW";
    h = "0.04 * safezoneH";
    color[] = {1,1,1,0.7};
    colorFocused[] = {1,1,1,1};
    colorHover[] = {1,1,1,1};
    colorPressed[] = {1,1,1,1};
    colorDisabled[] = {1,1,1,0.2};
    colorBackground[] = {0,0,0,0};
    colorBackgroundFocused[] = {0,0,0,0};
    colorBackgroundHover[] = {0,0,0,0};
    colorBackgroundPressed[] = {0,0,0,0};
    colorBackgroundDisabled[] = {0,0,0,0};
    textureChecked = "\A3\Ui_f\data\GUI\RscCommon\RscCheckBox\CheckBox_checked_ca.paa";
    textureUnchecked = "\A3\Ui_f\data\GUI\RscCommon\RscCheckBox\CheckBox_unchecked_ca.paa";
    textureFocusedChecked = "\A3\Ui_f\data\GUI\RscCommon\RscCheckBox\CheckBox_checked_ca.paa";
    textureFocusedUnchecked = "\A3\Ui_f\data\GUI\RscCommon\RscCheckBox\CheckBox_unchecked_ca.paa";
    textureHoverChecked = "\A3\Ui_f\data\GUI\RscCommon\RscCheckBox\CheckBox_checked_ca.paa";
    textureHoverUnchecked = "\A3\Ui_f\data\GUI\RscCommon\RscCheckBox\CheckBox_unchecked_ca.paa";
    texturePressedChecked = "\A3\Ui_f\data\GUI\RscCommon\RscCheckBox\CheckBox_checked_ca.paa";
    texturePressedUnchecked = "\A3\Ui_f\data\GUI\RscCommon\RscCheckBox\CheckBox_unchecked_ca.paa";
    textureDisabledChecked = "\A3\Ui_f\data\GUI\RscCommon\RscCheckBox\CheckBox_checked_ca.paa";
    textureDisabledUnchecked = "\A3\Ui_f\data\GUI\RscCommon\RscCheckBox\CheckBox_unchecked_ca.paa";
    tooltipColorText[] = {1,1,1,1};
    tooltipColorBox[] = {1,1,1,1};
    tooltipColorShade[] = {0,0,0,0.65};
    soundEnter[] = {"",0.1,1};
    soundPush[] = {"",0.1,1};
    soundClick[] = {"",0.1,1};
    soundEscape[] = {"",0.1,1};
};